aegeo:  
  name: "Alberta Geological Survey"
  locationurl: "http://ags.aer.ca/about-the-ags/contact-us.htm"
aginternet:  
  name: "Alberta Government Library - Internet"
  locationurl: "https://www.servicealberta.ca/alberta-government-library.cfm"
aglcap:  
  name: "Alberta Government Library - Capital Boulevard"
  locationurl: "https://www.servicealberta.ca/alberta-government-library.cfm"
aglcom:
  name: "Alberta Government Library - Commerce Place"
  locationurl: "https://www.servicealberta.ca/alberta-government-library.cfm"
aglgwl:
  name: "Alberta Government Library - Great West Life"
  locationurl: "https://www.servicealberta.ca/alberta-government-library.cfm"
agllb:
  name: "Alberta Government Library - Labour Building"
  locationurl: "https://www.servicealberta.ca/alberta-government-library.cfm"
aglmnc:
  name: "Alberta Government Library - Monenco Bldg Calgary"
  locationurl: "https://www.servicealberta.ca/alberta-government-library.cfm"
aglncc:
  name: "Alberta Government Library - Neil Crawford Centre"
  locationurl: "https://www.servicealberta.ca/alberta-government-library.cfm"
aglssp:
  name: "Alberta Government Library - 107 Street"
  locationurl: "https://www.servicealberta.ca/alberta-government-library.cfm"
agltpn:
  name: "Alberta Government Library - Telus Plaza North"
  locationurl: "https://www.servicealberta.ca/alberta-government-library.cfm"
ahsach:
  name: "Alberta Health Services - Alberta Children's Hospital"
  locationurl: "http://krs.libguides.com/aboutus/ach"
ahsahe:
  name: "Alberta Health Services - Alberta Hospital Edmonton"
  locationurl: 
ahscenten:  
  name: "Alberta Health Services - Centennial Centre"
  locationurl: 
ahsrah:  
  name: "Alberta Health Services - Royal Alexandra Hospital"
  locationurl: 
ahsctr15:
  name: "Alberta Health Services - Centre 15"
  locationurl:
ahskec:
  name: "Alberta Health Services - Kaye Edmonton Clinic"
  locationurl: "https://krs.libguides.com/aboutus/kec"
ahsreddr:
  name: "Alberta Health Services - Red Deer Regional Hospital"
  locationurl: "https://krs.libguides.com/aboutus/rdrh"
ahsrvgh:  
  name: "Alberta Health Services - Rockyview General Hospital"
  locationurl: "https://krs.libguides.com/aboutus/rgh"
ahssturg:
  name: "Alberta Health Services - Sturgeon Community Hospital"
  locationurl:
ahstbcc:
  name: "Alberta Health Services - Tom Baker Cancer Centre"
  locationurl: "http://krs.libguides.com/aboutus/tbcc"
ahserc:
  name: "Alberta Health Services"
  locationurl:
ahscenten:
  name: "Alberta Health Services"
  locationurl:
ahsint:
  name: "Alberta Health Services/Covenant Health - Internet"
  locationurl: "https://krs.libguides.com/home"
ahsglenrse:   
  name: "Alberta Health Services - Glenrose Rehabilitation Hospital"
  locationurl: "https://krs.libguides.com/aboutus/grh"
aitfcalg:
  name: "Alberta Innovates - Technology Futures - Calgary"
  locationurl:
aitfcfer:
  name: "Alberta Innovates - Technology Futures - C-FER Technologies"
  locationurl: "https://www.neoslibraries.ca/member-libraries/alberta-innovates/c-fer-library"
aitfc-fer:
  name: "Alberta Innovates - Technology Futures - C-FER Technologies"
  locationurl: "https://www.neoslibraries.ca/member-libraries/alberta-innovates/c-fer-library"
aitfdevon:
  name: "Alberta Innovates - Technology Futures - Devon"
  locationurl: 
aitfmw:
  name: "Alberta Innovates - Technology Futures - Mill Woods"
  locationurl: "https://www.neoslibraries.ca/member-libraries/alberta-innovates/mill-woods-library/"
aitfveg:
  name: "Alberta Innovates - Technology Futures - Vegreville"
  locationurl: "https://www.neoslibraries.ca/member-libraries/alberta-innovates/vegreville-library-2/"
burman:
  name: "Burman University"
  locationurl: "https://www.burmanu.ca/library"
concordia:
  name: "Concordia University of Edmonton"
  locationurl: "http://library.concordia.ab.ca"
concordsem:   
  name: "Concordia Lutheran Seminary"
  locationurl: "​http://www.concordiasem.ab.ca/research/library_information.php​"
covenantgn: 
  name: "Covenant Health - Grey Nuns Community Hospital"
  locationurl: "​https://www.covenanthealth.ca/corporate-information/library-services​"
covenantmh:   
  name: "Covenant Health - Misericordia Community Hospital"
  locationurl: "​https://www.covenanthealth.ca/corporate-information/library-services​"
cross:
  name: "Cross Cancer Institute"
  locationurl:
gprcgp:
  name: "Grande Prairie Regional College - Grande Prairie"
  locationurl: "https://www.gprc.ab.ca/library"
gprcfrvw:   
  name: "Grande Prairie Regional College - Fairview"
  locationurl: "https://www.gprc.ab.ca/library"
gprcint:   
  name: "Grande Prairie Regional College - Internet"
  locationurl: "https://www.gprc.ab.ca/library"
grmacacc:
  name: "MacEwan University - Alberta College Campus"
  locationurl: "https://library.macewan.ca/"
grmaccac:
  name: "MacEwan University - Centre for Arts & Communications"
  locationurl: "https://library.macewan.ca/"
grmacint:
  name: "MacEwan University - Internet"
  locationurl: "https://library.macewan.ca/"
grmactsv:
  name: "MacEwan University - Technical Services"
  locationurl: "https://library.macewan.ca/"
grmacsoc:
  name: "MacEwan University - South Campus"
  locationurl: "https://library.macewan.ca/"
grmacewan:
  name: "MacEwan University - City Centre Campus"
  locationurl: "https://library.macewan.ca/"
justiceca:   
  name: "Justice Canada"
  locationurl: 
keyano:   
  name: "Keyano College"
  locationurl: "http://www.keyano.ca/Services/Library​"
kings:
  name: "The King's University College"
  locationurl: "https://www.kingsu.ca/library"
lakelndin:
  name: "Lakeland College Internet"
  locationurl: "​​https://web.lakelandcollege.ca/commons/library/​"
lakelndll:
  name: "Lakeland College Lloydminster"
  locationurl: "https://www.neoslibraries.ca/member-libraries/lakeland/lloydminster-campus-library/"
lakelndvr:
  name: "Lakeland College Vermilion"
  locationurl: "https://www.neoslibraries.ca/member-libraries/lakeland/vermilion-campus-library/​"
neosfree:
  name: "NEOS Free Internet Resources"
  locationurl: 
newman:   
  name: "Newman Theological College"
  locationurl: "https://www.newman.edu/Library"
nlcgr:
  name: "Northern Lakes College - Grouard"
  locationurl: "https://www.northernlakescollege.ca/current-students/library-services"
nlcint:
  name: "Northern Lakes College - Internet"
  locationurl: "https://www.northernlakescollege.ca/current-students/library-services"
nlcsl:
  name: "Northern Lakes College - Slave Lake"
  locationurl: "https://www.northernlakescollege.ca/current-students/library-services"
norqmain:
  name: "NorQuest College - Main Building"
  locationurl: "https://library.norquest.ca"
norqwest:   
  name: "NorQuest College - Westmount"
  locationurl: "https://library.norquest.ca"
olds:
  name: "Olds College"
  locationurl: "​https://www.oldscollege.ca/student-life/learning-commons/index.html​"
reddeerc:
  name: "Red Deer College"
  locationurl: "https://rdc.ab.ca/current-students/library"
taylor:
  name: "Taylor College and Seminary"
  locationurl: "http://www.taylor-edu.ca/seminary/library"
vanguard:
  name: "Vanguard College"
  locationurl: "http://www.vanguardcollege.com/library"
uaarchives:
  name: "University of Alberta Archives"
  locationurl: "https://www.library.ualberta.ca/locations/archives"
uaaug:
  name: "University of Alberta Augustana"
  locationurl: "https://www.library.ualberta.ca/locations/augustana"
uabard:
  name: "University of Alberta Research and Collections Resource Facility"
  locationurl: "https://www.library.ualberta.ca/locations/rcrf"
uabsj:
  name: "University of Alberta Bibliotheque Saint-Jean"
  locationurl: "https://www.library.ualberta.ca/locations/bsj"
uabusiness:
  name: "University of Alberta Winspear Business"
  locationurl: "https://www.library.ualberta.ca/locations/winspear"
uaeduc:
  name: "University of Alberta HT Coutts Education"
  locationurl: "https://www.library.ualberta.ca/locations/coutts"
uahlthsc:   
  name: "University of Alberta JW Scott Health Sciences"
  locationurl: "https://www.library.ualberta.ca/locations/scott"
uahss:
  name: "University of Alberta Rutherford-Humanities & Social Science"
  locationurl: "https://www.library.ualberta.ca/locations/rutherford"
uainternet:
  name: "University of Alberta Internet"
  locationurl: "https://www.library.ualberta.ca/services/off-campus-access"
ualaw:
  name: "University of Alberta JA Weir Law"
  locationurl: "https://www.library.ualberta.ca/locations/law"
uamath:
  name: "University of Alberta Mathematics"
  locationurl: "https://www.library.ualberta.ca/locations/cameron"
uascitech:
  name: "University of Alberta Cameron - Science & Technology"
  locationurl: "https://www.library.ualberta.ca/locations/cameron"
uasjc:
  name: "University of Alberta St Joseph's College"
  locationurl: "https://www.library.ualberta.ca/locations/stjosephs"
uaspcoll:
  name: "University of Alberta Bruce Peel Special Collections"
  locationurl: "https://www.library.ualberta.ca/locations/bpsc"
uatechserv:
  name: "University of Alberta Bibliographic Services"
  locationurl:
uarcrf:
  name: "University of Alberta Research and Collections Resource Facility"
  locationurl: "https://www.library.ualberta.ca/locations/rcrf"
usic tech lab:
  name: "University of Alberta Cameron - Science & Technology - Lab"
  locationurl:
